name: cool_linter
description: linter for analyzing dart code by RegExp pattern
version: 1.1.0
homepage: https://github.com/jWinterDay/cool_linter
repository: https://github.com/jWinterDay/cool_linter
issue_tracker: https://github.com/jWinterDay/cool_linter/issues

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  analyzer: ^1.7.0 # ^2.0.0
  analyzer_plugin: ^0.6.0
  collection: ^1.15.0
  yaml: ^3.1.0
  meta: ^1.7.0
  glob: ^2.0.1
  path: ^1.8.0
  pub_semver: ^2.0.0

dev_dependencies:
  test: ^1.17.10
  pedantic: ^1.11.1

# dependency_overrides:
#   analyzer: ^2.0.0 # ^1.7.0