name: cool_linter
description: cool_linter
version: 0.0.1
homepage: https://github.com/jWinterDay/cool_linter

environment:
  # sdk: ">=2.12.0 <3.0.0"
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  # analyzer: "^1.1.0"
  # analyzer_plugin_fork: "^0.5.0"
  # analyzer: ^1.3.0
  # analyzer_plugin: ^0.5.0

  analyzer: '>=0.39.3 <0.42.0'
  analyzer_plugin: '>=0.2.1 <0.5.0'
  ansicolor: ^1.1.0
  args: ^1.4.4
  code_checker: '>=0.3.6 <0.3.7'
  crypto: ^2.0.6
  glob: ^1.1.7
  html: '>=0.13.4 <1.0.0'
  meta: ^1.1.6
  path: ^1.6.2
  quiver: ^2.0.0
  source_span: ^1.4.1
  yaml: ^2.1.5

dev_dependencies:
  # build_test: ^2.0.0
  # pedantic: ^1.9.2
  # pedantic: ^1.11.0
  # test: ^1.16.8

  test: ^1.15.3
  pedantic: ^1.9.2