name: cool_linter
description: cool_linter
version: 0.0.1
homepage: https://github.com/jWinterDay/cool_linter

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  analyzer: ^1.3.0
  analyzer_plugin: ^0.5.0

dev_dependencies:
  build_test: ^2.0.0
  pedantic: ^1.9.2
  test: ^1.15.3