name: cool_linter_plugin_loader
description: cool linter plugin loader
version: 0.0.1

environment:
  sdk: ">=2.8.0 <3.0.0"

# environment:
#   sdk: ">=2.12.0 <3.0.0"

dependencies:
  cool_linter:
    git: https://github.com/jWinterDay/cool_linter
    
